# -*- coding: utf-8 -*-
{
    'name': "Kwantify Tour",
    'summary': """ Kwantify Tour """,
    'description': """ Kwantify Tour """,
    'author': "CSM Technologies",
    'website': "https://www.csm.tech",
    'category': 'Kwantify/Employee',
    'version': '0.1',
    'depends': ['kwantify', 'kw_project', 'kw_employee', 'kw_fiscal_year_sequence_extensible','kw_hr_attendance', 'kw_accounting'],
    'data': [
        'security/kw_tour_security.xml',
        'security/ir.model.access.csv',
        
        # data file section
        'data/kw_tour_type_data.xml',
        'data/kw_tour_others_mail.xml',
        'data/kw_tour_expense_type_data.xml',
        'data/kw_tour_travel_mode_data.xml',
        'data/kw_tour_approval_workflow_data.xml',
        'data/kw_tour_settlement_workflow_data.xml',
        'data/kw_tour_settlement_mail_data.xml',
        'data/kw_tour_cancellation_workflow_data.xml',
        'data/kw_tour_sequence_no.xml',
        'data/kw_tour_settlement_reminder_scheduler.xml',
        'data/kw_tour_settlement_reminder_mail.xml',
        'data/kw_apply_tour_mail_template.xml',
        'data/kw_tour_cancellation_mail_data.xml',
        'data/kw_tour_settlement_mail_data.xml',
        # 'data/kw_tour_da_category_data.xml',
        'data/kw_tour_classification_type_data.xml',
        # 'data/kw_tour_city_configuration_data.xml',
        'data/kw_tour_ancillary_expense_data.xml',
        'data/kw_pending_action_mail_template.xml',
        'data/kw_tour_advance_request_workflow_data.xml',
        'data/kw_tour_advance_request_email_template.xml',
        'data/kw_tour_return_date_notification_mail_template.xml',
        'data/project_system_parameter.xml',
        'data/kw_tour_travel_prerequisite_data.xml',
        'data/kw_tour_exchange_rate_schedular.xml',
        'data/kw_tour_budget_head_data.xml',
        'data/passport_update_reminder_mail.xml',
        'data/kw_tour_project_budget_scheduler.xml',
        'data/kw_tour_project_budget_limit_mail.xml',
        'data/csg_tour_apply_email_template.xml',
        # data file section

        # view section
        'views/kw_tour_menu.xml',
        'views/kw_tour_city_view.xml',
        'views/kw_tour_classification_type_view.xml',
        'views/kw_tour_da_category_view.xml',
        'views/kw_tour_type_view.xml',
        'views/kw_tour_view.xml',
        'views/kw_tour_take_action_view.xml',
        'views/kw_tour_details_view.xml',
        'views/kw_tour_accomodation_view.xml',
        'views/kw_tour_ancillary_expense_details_view.xml',
        'views/kw_tour_expense_type_view.xml',
        'views/kw_tour_classfication_expense_view.xml',
        'views/kw_tour_ancillary_expenses_view.xml',
        'views/kw_tour_settlement_details_view.xml',
        'views/kw_tour_settlement_view.xml',
        'views/kw_tour_settlement_take_action_view.xml',
        'views/kw_tour_cancellation_view.xml',
        'views/kw_tour_travel_expense_details_view.xml',
        'views/view_tour_settlement.xml',
        'views/kw_tour_settlement_remark_view.xml',
        'views/kw_tour_city_days_spend_views.xml',
        'views/kw_tour_travel_details.xml',
        'views/kw_tour_remark_views.xml',
        'views/kw_tour_view_all_tour.xml',
        'views/kw_tour_settlement_payment_view.xml',
        'views/kw_apply_tour_action_log_views.xml',
        'views/kw_tour_settlement_action_log_views.xml',
        'views/templates.xml',
        'views/kw_tour_guest_house_view.xml',
        'views/kw_tour_advance_given_log_view.xml',
        'views/kw_tour_advance_request_view.xml',
        'views/kw_tour_advance_request_status_view.xml',
        'views/kw_tour_cancellation_status_view.xml',
        'views/kw_tour_advance_request_action_log_view.xml',
        'views/kw_tour_advance_request_take_action_view.xml',
        'views/kw_tour_settlement_total_expense_view.xml',
        'views/kw_tour_res_config_setting.xml',
        'views/kw_tour_travel_ticket_view.xml',
        'views/kw_tour_travel_prerequisite_view.xml',
        'views/kw_tour_budget_head.xml',
        'views/kw_tour_exchange_rate_view.xml',
        'views/kw_tour_update_passport_wizard.xml',
        'views/kw_tour_passport_emp_view.xml',
        'views/kw_tour_project_budget_view.xml',
        'views/kw_tour_others.xml',
        'views/kw_group_tour_csg_view.xml',
        'views/kw_treasury_budget_view.xml',
        'views/kw_tour_csuite.xml',

        # reports section
        'reports/kw_apply_report_view.xml',
        'reports/kw_tour_cancellation_report_view.xml',
        'reports/kw_tour_settlement_report_view.xml',
        'reports/kw_settlement_claim_pdf_report.xml',
        'reports/kw_tour_budget_report_view.xml',
        'reports/tour_status_report_view.xml',
        'reports/kw_tour_settlement_expenses_view.xml',
        'reports/kw_tour_one_report_view.xml',
        # 'views/kw_tour_reschedule_log_view.xml',
        # view section

        # template section
        'templates/approval_success_template.xml',
        # template section

        # wizard section
        'wizards/kw_tour_settlement_claim_wizard_view.xml',
        # wizard section
    ],
    'qweb':[
        'static/src/xml/form_view_button.xml',
        ]
}
