{
    'name' : "BSSCL Employee Appriasal / बिहार सरिफ स्मार्ट सिटी लिमिटेड कर्मचारी मूल्यांकन",
    'summary' : """Bihar sarif smart city limited Appraisal module / बिहार सरिफ स्मार्ट सिटी लिमिटेड मूल्यांकन मापांक """,
    'description' : """Hr employee appraisal management""",
    'version': '14.0',
    'category' : "Web Application",
    'author' : "BSSCL / बिहार सरिफ स्मार्ट सिटी लिमिटेड",
    'license': 'LGPL-3',
    'website' : "https://www.bsscl.bihar.co.in",
    'depends' : ['base','hr','fetchmail','bsscl_fiscal_year'],
    'data' : [
            'security/security.xml',
            'security/ir.model.access.csv',
            'wizard/create_appraisal.xml',
            # 'wizard/appraisal_raise_query.xml',
            'views/appraisal_form.xml',
            'data/appraisal_mail_template.xml',
            'views/appraisal_rating.xml',
            'views/appraisal_template.xml',
            'views/hr_employee_inherit.xml',
            'views/hr_job_inherit.xml',
            'views/annex_template.xml',
            'views/print_template.xml',
            'views/appraisal_menu.xml',
            'views/assets.xml',
            ],
    'application' : True,
    'auto_install' : False,
    'installable' : True,
    'sequence' : 1,
}