# -*- coding: utf-8 -*-
from . import res_config
from . import hr_job_in
from . import kw_recruitment_experience
from . import kw_recruitment_info_source
from . import kw_walk_in_meeting_details
from . import kw_recruitment_walk_in_meeting
from . import hr_applicant_in
from . import calender_event_in
# from . import kw_survey_type_master
from . import survey_survey_in
from . import survey_user_input_in
from . import kw_hr_job_positions
from . import kw_job_category
from . import kw_industry_type
from . import kw_qualification_master
from . import kw_panel_members_master
from . import kw_recruitment_location
from . import kw_ir_attachment
from . import calendar_attendee_in
from . import requisition_category
from . import requisition_skill
from . import kw_requisition
from . import kw_source_master
from . import kw_recruitment_doc_store
from . import res_users
from . import hr_applicant_offer
from . import cv_skills_master
from . import cv_skills_api_log
from . import upload_cv
from . import kw_notify_to_panel
from . import referred_employee_and_applicant_report
from . import mrf_approver_department_config
from . import kw_mrf_employee_grade_access
from . import hr_applicant_educational_and_work_experience
from . import manpower_indent_form
# from . import kw_mif_report
from . import otp_max_attempt_log
from . import hiring_dashboard
from . import hr_discussion_applicant_details
from . import cv_rating_api_response_log
from . import jd_skils_master
