{
    'name': "Kwantify Resource Management",
    'summary': "Employee Information",
    'description': "Employee MIS",
    'author': "CSM Technologies",
    'website': "https://www.csmpl.com",
    'category': 'Kwantify/Human Resources',
    'version': '0.1',

    'depends': ['base', 'kw_employee', 'payroll_inherit','kw_eos'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',

        'data/ir_sequence_data.xml',
        'data/sbu_tagging_email.xml',
        # 'data/rcm_mail_template.xml',
        'data/central_bench_engagement.xml',
        'data/central_bench_mail_to_sbu.xml',
        'data/end_date_reminder_mail.xml',
        'data/end_date_reminder_cron.xml',
        'data/sync_consultant_cron.xml',
        'views/project_date_reminder_cron.xml',

        'views/hrms_budget_mapping.xml',
        'wizard/sbu_bench_resource_filter_wizard.xml',
        'wizard/mapped_to_sbu_filter_wizard.xml',
        'wizard/sbu_tagging_filter_wizard.xml',
        'views/sbu_resource_tagging.xml',
        'wizard/budget_mapping_filter_wizard.xml',
        'wizard/resource_qty_update_wizard.xml',
        'wizard/forecasted_report_wizard.xml',
        # 'wizard/sbu_approve_remark.xml',

        'views/sbu_resource_mapping.xml',
        'views/kw_resource_release_reasons.xml',
        'views/bench_employee.xml',
        'views/project_time_management.xml',
        'views/employee.xml',
        'views/kw_sbu_report_employee.xml',
        'views/sbu_count_report_employee.xml',
        'views/asset.xml',
        'views/sbu_requisition.xml',
        'views/sbu_tag_untag_log.xml',
        # 'views/project_project_views.xml',
        'views/kw_project_resource_count_report_view.xml',
        'views/forecasted_release_report.xml',
        'views/resource_wise_project.xml',
        'views/project_wise_resource.xml',
        'views/technology_wise_resource_count.xml',
        'views/technology_wise_resource_report_views.xml',
        'views/update_resource_skill.xml',
        'views/res_config_setting.xml',
        # 'views/project_report.xml',
    #     'views/location_wise_report.xml',
    #     'views/emp_department_report.xml',
    #     'views/employee_skill_wise_report.xml',
    #     'views/sbu_designation_master.xml',
    #     'views/vertical_sbu_report.xml',
    #     'views/gap_status_report.xml',
    #     'views/requirment_report.xml',
    #     'views/employment_type_wise_report.xml',
          'views/unit_bench.xml',
          'views/horizontal_resource_report.xml',
          'views/sbu_resource_report.xml',
          'views/engagement_plan_master.xml',
          'views/central_bench_engagement.xml',
          'views/central_bench_weekly_ctc_report.xml',
          'views/central_bench_report_history.xml',
          'views/sbu_project_wise_head_count.xml',
          'views/sbu_wise_designation.xml',
          'views/rcm_dashboard_views.xml',
          'views/sbu_wise_designation.xml',
          'views/kw_all_emp_skill_view.xml',
          'views/kw_all_emp_skill_expertise_template.xml',

          'data/resource_mapping_parameter.xml',
          'views/resource_mapping_data.xml',
          'views/resource_skill_data.xml',
          'views/workforce_analytics_report.xml',
          'views/capability_report.xml',
          'views/skill_dashboard_report_master.xml',
          'views/sync_consultant_data_view.xml',
        #   'views/sbu_horizontal_tagging.xml',
         
          
          'views/menu.xml',
    ],
    'qweb': ["static/src/xml/rcm_dashboard.xml",
            "static/src/xml/work_force_analytics_dashboard.xml",
            "static/src/xml/skill_data_dashboard.xml",
            "static/src/xml/list_button.xml",
            'static/src/xml/sync_consultant_details.xml',
            'static/src/xml/forecasted_release_report_web.xml',
            'static/src/xml/forecasted_release_report_client_view.xml',
           ],       
    
    'application': True,
    'installable': True,
    'auto_install': False,
}

