from . import acceptance_trigger
from . import acceptance_trigger_line
from . import acceptance_check_list_category
from . import acceptance_check_list
from . import acceptance_inspection
from . import product_product
from . import product_template
from . import product_category
from . import project
from . import res_users
