from . import employee
from . import city
from . import country
from . import state
from . import training
from . import language
from . import sale_order
from . import employee_payslip
from . import delegation_inheritance
from . import blood_group