# See LICENSE file for full copyright and licensing details.

{
    'name': 'Applicant Process',
    'version': '11.0.0.1.0',
    'category': 'Human Resources',
    'sequence': 90,
    'license': "AGPL-3",
    'summary': 'Applicant and Employee Subsections, Training',
    "author": "Serpent Consulting Services Pvt. Ltd.",
    "website": "http://www.serpentcs.com",
    "maintainer": "Serpent Consulting Services Pvt. Ltd.",
    'depends': ['hr_recruitment', 'document','stpi_contract_pr','category_religion','hr_skills','hr_skills_applicant','groups_inherit'],
    'data': [
        'security/ir.model.access.csv',
        'security/applicant_security.xml',
        'wizard/select_training_view.xml',
        'wizard/change_stage_views.xml',
        'views/templates.xml',
        'views/hr_recruitment_views.xml',
        'views/hr_recruitment_employee_views.xml',
        'views/hr_applicant_inherited.xml',
        'views/training_views.xml',
        'views/applicant_profile_report_view.xml',
        'views/new_applicant_template.xml',
        'report/report_view.xml',
        'report/offer_letter_templates.xml',
        'report/report.xml',
        'data/mail_data.xml',
        'wizard/applicant_bulk_shift_views.xml',
        'wizard/applicant_refuse_reason_view.xml',
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
