# -*- coding: utf-8 -*-
{
    'name': "Kwantify Recruitment Calendar",
    'summary': "Recruitment Calendar Report",
    'description': "Recruitment Calendar Reports",
    'author': "CSM Technologies",
    'website': "https://www.csm.tech",
    'category': 'Kwantify/Human Resources',
    'version': '0.1',
    'depends': ['base', 'kw_recruitment'],
    'data': [
        'security/kw_recruitment_security.xml',
        'data/kw_recruitment_calendar_sequence.xml',
        'data/kw_recruitment_calendar_action_email.xml',
        'security/ir.model.access.csv',
        'views/kw_recruitment_caledar_view.xml',
        'views/template.xml',
        'wizards/calendar_summary_wizard.xml',
        'wizards/treasury_budget_approval_wizard.xml',
        'views/kw_calendar_summary_view.xml',
        'views/recruitment_budget_view.xml',
        'views/kw_department_inherit.xml',
        'views/treasury_budget.xml',
        'views/project_budget.xml',
        'views/budget_take_action.xml',
        'views/resource_tagging.xml',
        'views/calendar_take_action.xml',
        'views/menu.xml',
    ],
    'qweb': [
        "static/src/xml/recruitment_budget_template.xml",
        #'static/src/xml/recruitment_calender_details.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}
