{
    'name': "BSSCL Tour / बिहार शरीफ स्मार्ट सिटी लिमिटेड यात्रा ",
    'summary': """BSSCL Tour module / बीएसएससीएल यात्रा मापांक """,
    'description': "Tour management module for BSSCL / बीएसएससीएल के लिए यात्रा प्रबंध मापांक",
    'version': '14.0',
    'category' : "Web Application",
    'website': "https://www.bsscl.bihar.co.in",
    'author': 'BSSCL / बिहार सरिफ स्मार्ट सिटी लिमिटेड',
    'depends' : ['base','hr'],
    'data':['security/ir.model.access.csv',
            'security/tour_security.xml',
            'data/tour_mail_template.xml',
            'wizard/tour_rejection.xml',
            'views/bsscl_expense_type.xml',
            'views/bsscl_guest_house.xml',
            'views/bsscl_medical_expense.xml',
            'views/bsscl_telephone_bill_expense.xml',
            'views/bsscl_tour_advance.xml',
            'views/bsscl_tour_allowance_conf.xml',
            'views/bsscl_tour_classification_expense.xml',
            'views/bsscl_tour_da.xml',
            'views/bsscl_tour_details.xml',
            'views/bsscl_tour_ravel_expense_details.xml',
            'views/bsscl_tour_settlement.xml',
            'views/bsscl_tour.xml',
            'views/tour_city.xml',
            'views/tour_travel_booking.xml',
            'views/menu.xml',],
    'application': True,
    'installable': True,
    'auto_install': False,
    'sequence': 1,
}