{
    "name": "Acceptance Management",
    "version": "14.0.1.1.0",
    "category": "Acceptance Management",
    "license": "AGPL-3",
    "summary": "Generic infrastructure for acceptance check list.",
    "author": "Geotechnosoft",
    "depends": ["product", "project", "base", "web", "contract"],
    "data": [
        "data/acceptance_data.xml",
        "security/acceptance_security.xml",
        "security/ir.model.access.csv",
        "data/activity_data.xml",
        "data/email_template.xml",
        "data/reminder_cron.xml",
        "wizard/acceptance_check_list_wizard_view.xml",
        "wizard/rejection_reason.xml",
        "wizard/submit_for_approval_view.xml",
        "views/acceptance_menus.xml",
        "views/acceptance_inspection_view.xml",
        "views/check_list_category_view.xml",
        "views/check_list_view.xml",
        "views/acceptance_trigger_view.xml",
        "views/product_template_view.xml",
        "views/product_category_view.xml",
        "views/project_view.xml",
    ],
    "demo": [],
    "installable": True,
}
