# -*- coding: utf-8 -*-
{
    'name': 'Kwantify TDS',
    'version': '1.0.1',
    'summary': 'Kwantify TDS',
    'category': 'Kwantify/Human Resources',
    'author': 'CSM Technologies',
    'maintainer': 'Kwantify',
    'company': 'CSM Technologies',
    'website': 'https://www.csm.tech',
    'depends': ['base', 'hr', 'hr_payroll',],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/user_tds_fillup_mail_template.xml',
        'views/user_tds_fillup_view.xml',
        'views/finance_tds_tax_computation_view.xml',
        'views/user_view_tax_bifurcation.xml',
        'views/yearly_hr_declaration.xml',
        'views/hr_declaration.xml',
        'views/asset.xml',
        'views/city_wise_hra_config.xml',
        'data/email_template.xml',
        'data/yearly_declaration_cron.xml',
        'data/hr_declaration_cron.xml',
        'data/saving_master.xml',
        'views/tax_slab.xml',
        'views/finance_approval_mail.xml',
        'views/res_config_settings.xml',
        'views/compute_tax_action.xml',
        'data/config_parameter.xml',
        'views/all_hr_declaration.xml',
        'report/hr_declaration_report.xml',
        'views/update_declaration_wizard.xml',
        'views/menu.xml',
        'views/hr_declaration_log.xml',
        'views/tds_fy_wise_report.xml'
    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
