# -*- coding: utf-8 -*-
{
    'name': 'Kwantify Payroll',
    'summary': """Kwantify Payroll""",
    'description': """Kwantify Payroll""",
    'category': 'Kwantify/Human Resources',
    'author': 'kwantify@csm.tech',
    'company': 'CSM Technologies',
    'maintainer': 'CSM Technologies ',
    'website': "https://www.csm.tech",
    'version': '1.0.1',
    'depends': ['base', 'hr', 'hr_contract', 'hr_payroll', 'l10n_in_hr_payroll', 'kw_employee', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',

        'data/payroll_salary_rule_data.xml',
        'data/payroll_structure_data.xml',
        # 'data/relationship_master.xml',
        'data/create_contract.xml',
        'data/new_salary_rule.xml',
        'data/contract_end_scheduler.xml',
        'views/lunch_expenses.xml',
        'wizard/hr_payment_advices_by_employees_views.xml',
        'wizard/hr_approve_insurance.xml',
        'wizard/kw_payroll_report.xml',
        'views/payment_advices.xml',
        'views/health_insurance_mail_template.xml',
        # 'views/payroll_structure_inherit.xml',
        'views/relationship_insurance_amount.xml',
        'views/employee_relationship_insurance.xml',
        'views/add_health_insurance_dependencies.xml',
        'views/health_insurance.xml',
        'views/allowance_allocation_master.xml',
        'views/contract_inherit.xml',
        # 'views/relationship_master.xml',
        'views/hr_payroll.xml',
        'wizard/payslip_otp_validation.xml',
        'views/kw_employee_inherit.xml',
        'views/res_config_settings.xml',
        # 'views/contractual_employee.xml',
        'views/block_salary.xml',
        'data/esi_scheduler.xml',
        'views/kw_payroll_monthly_attendance_report_view.xml',
        'reports/hr_payroll_salary_report.xml',
        'reports/kw_ctc_report.xml',
        # 'views/hr_payroll_professional_tax.xml',
        'reports/net_ctc_report.xml',
        'reports/allowance_report.xml',
        'reports/salary_disburse_report.xml',
        'reports/other_advance_download_report.xml',
        'reports/salary_advance_report_download.xml',
        'reports/salary_advance_report.xml',
        'reports/compiled_salary_report.xml',
        'reports/tds_report_download.xml',
        'reports/other_advance_report.xml',
        'reports/monthly_salary_report.xml',
        'reports/tds_report.xml',
        'reports/csmpl_compiled_salary_report.xml',
        'views/insurance_premium_config.xml',
        'views/payroll_report_wiz.xml',
        'reports/kw_deduction_report.xml',
        'reports/kw_allowance_report.xml',
        'reports/ghi_details_report.xml',
        'views/kw_payslip_ledger.xml',
        'wizard/get_payroll_data_from_v5.xml',
        'wizard/get_attendance_data_from_v5.xml',
        'wizard/get_advance_data_from_v5.xml',
        'data/payroll_data.xml',
        'data/attendance_data.xml',
        'data/get_advance_data.xml',
        "wizard/kw_payroll_api_log.xml",
        "wizard/advance_data_log.xml",
        "wizard/kw_payroll_attendance_api_log.xml",
        "views/health_insurance_form_web_page.xml",
        'views/health_insurance_configuration.xml',
        'reports/employee_without_dependent.xml',
        'reports/professional_tax_report.xml',
        'reports/employee_pf_report.xml',
        'reports/employee_esi_report.xml',
        'reports/salary_disburse_report.xml',
        'reports/epf_calculatation_report.xml',
        # 'wizard/download_epf_report.xml',
        'reports/bulk_esi_calculation_report.xml',
        'data/insurance_configure_data.xml',
        'reports/epf_admin_charges_report_view.xml',
        'wizard/download_esi_report.xml',
        'wizard/update_emp_salary.xml',
        'reports/employee_esi_calc_report.xml',
        'views/qweb/bank_update_form.xml',
        'views/qweb/nps_update_form.xml',
        'views/bank_update_details.xml',
        'reports/c1_salary_report_filter.xml',
        'reports/batch_wise_bulk_report.xml',
        'reports/form_12_b.xml',
        'reports/employee_dept_ctc_count_report.xml',
        'reports/kw_manpower_cost_report.xml',
        'reports/emp_health_insurance_emi_details.xml',
        'reports/nps_pran_details.xml',
        'reports/nps_contribution_details.xml',
        'views/kw_payroll_zero_payslip.xml',
        'views/payroll_increment.xml',
        'views/nssf_master.xml',
        'views/kenya_tax_slab.xml',
        'views/pp_lta_slab.xml',
        'views/nhif_master.xml',
        'views/tax_master.xml',
        'views/consolidate_report.xml',
        'views/non_esi_employee.xml',
        # 'views/department_access_config.xml',
        # 'wizard/payslip_pdf_wizard.xml',
        'wizard/first_last_payslip.xml',
        'wizard/update_emp_insurance_doc.xml',
        'views/menu.xml',
        'views/email/dependant_request_and_approval.xml',
        'views/email/nps_mails.xml',
        'views/nps_employee_data_view.xml',
        'data/create_employee_nps_scheduler.xml',
        

    ],
   
    # 'demo': [
    #     'data/previous_occupation_organisation_type_demo.xml',
    #
    # ],

    'installable': True,
    'application': True,
    'auto_install': False,

}
