# -*- coding: utf-8 -*-
{
    'name': "Kwantify Gallery",
    'summary': "Used to view Image Gallery",
    'description': "Used to store, manage and view Images in Website Gallery view and Kanban view.",
    'author': "CSM Technologies",
    'website': "https://www.csm.tech",
    'category': 'Kwantify/Human Resources',
    'version': '0.1',
    'depends': ['website', 'web', 'kw_web_notify', ],
    'data': [
        'security/kw_gallery_security.xml',
        'security/ir.model.access.csv',
        'views/assets.xml',
        'views/kw_image_gallery.xml',
        'views/kw_image_category.xml',
        # 'views/kw_website_menu_data.xml',
        'views/kw_image_album.xml',
        'views/kw_albums_approval.xml',
        'views/kw_image_gallery_menu_items.xml',
        'views/kw_gallery_assets.xml',
        'views/kw_images.xml',
        'views/kw_display_image_gallery.xml',
        'views/kw_website_gallery_templates.xml',
        'views/kw_gallery_search_panel.xml',
    ],
    'qweb': ['static/src/xml/kw_gallery_template.xml'],
    'application': True,
    'installable': True,
    'auto_install': False,
}
