{
    'name' : "Employee Appriasal",
    'summary' : """Employee Appraisal module""",
    'description' : """Hr employee appraisal management""",
    'version': '14.0',
    'category' : "Web Application",
    'author' : "Ajay",
    'license': 'LGPL-3',
    'website' : "https://employee.appraisal.com",
    'depends' : ['base','hr','fetchmail','fiscal_year'],
    'data' : [
            'security/security.xml',
            'security/ir.model.access.csv',
            'wizard/create_appraisal.xml',
            # 'wizard/appraisal_raise_query.xml',
            'views/appraisal_form.xml',
            'data/appraisal_mail_template.xml',
            'views/appraisal_rating.xml',
            'views/appraisal_template.xml',
            'views/hr_employee_inherit.xml',
            'views/hr_job_inherit.xml',
            'views/annex_template.xml',
            'views/print_template.xml',
            'views/appraisal_menu.xml',
            'views/assets.xml',
            ],
    'application' : True,
    'auto_install' : False,
    'installable' : True,
    'sequence' : 1,
}