# -*- coding: utf-8 -*-
from . import kw_eos
from . import res_config_setting
from . import hr_employee
from . import kw_resignation 
from . import kw_resignation_type_master 
from . import kw_no_objection 
from . import emp_group 
from . import notice_period_master 
from . import kw_eos_QA
from . import kw_eos_checklist
from . import hr_employee_clearance
from . import employee_exit_interview
from . import kw_emp_archieve
from . import kw_offboarding_type_master
from . import kw_user_type_master
from . import kw_termination_reason_master
from . import kw_eos_user_details
from . import kw_eos_checklist_log
from . import kw_clearance_log
from . import kw_resignation_letter
from . import attrition_dashboard