from . import it_rule_master
from . import hr_declaration
from . import n_hr_payroll
from . import yearly_hr_declaration
from . import yearly_notsubmitted_dec
from . import tax_slab
from . import res_config_settings
from . import all_hr_declaration
from . import city_wise_hra_config
from . import update_declaration_wizard
from . import form_16_report
from . import hr_declaration_log