# -*- coding: utf-8 -*-
{
    'name': "Kwantify Training",
    'summary': """
        Kwantify Training
     """,
    'description': """ 
        Kwantify Training
     """,
    'author': "CSM Technologies",
    'website': "https://www.csm.tech",
    'category': 'Kwantify/Employee',
    'version': '0.1',

    'depends': ['base', 'kw_auth', 'hr', 'survey', 'kwantify', 'kw_dms', 'kw_skill_assessment',
                'kw_account_fiscal_year', 'kw_dynamic_workflow','performance_improvement_plan'],
    'data': [
        'security/kw_training_security_groups.xml',
        'security/ir.model.access.csv',
        'data/kw_generate_certificate_pdf.xml',
        'data/kw_certfication_mail_template.xml',
        'data/kw_training_dynamic_workflow_data.xml',
        'data/kw_training_feedback_survey.xml',
        'data/kw_training_plan_mail.xml',
        'data/kw_training_announcement_template.xml',
        'views/kw_training_menu.xml',
        'views/kw_training_trainer_feedback_views.xml',
        'views/kw_training_view.xml',
        'views/kw_training_plan_view.xml',
        'views/kw_training_schedule_view.xml',
        'views/kw_training_feedback_view.xml',
        'views/calendar_client_action.xml',
        'views/kw_my_training_view.xml',
        'views/kw_training_approve_view.xml',
        'views/kw_training_approval_remark_views.xml',
        'views/kw_training_material_view.xml',
        'views/survey_templates/kw_training_feedback_template.xml',
        'views/kw_skill_ques_set_form.xml',
        'views/kw_training_attendance_view.xml',
        'views/kw_training_attendance_detail_view.xml',
        'report/kw_training_report.xml',
        'report/kw_training_wise_report1.xml',
        'report/kw_training_wise_report2.xml',
        'report/kw_skill_enhancement_report.xml',
        'report/kw_participant_wise_report.xml',
        'report/kw_fiscal_year_wise_traning_report.xml',
        
        'views/kw_training_assessment_result_view.xml',
        'views/kw_training_assessment_view.xml',
        'views/kw_training_score_details_view.xml',
        'views/kw_training_score_view.xml',
        'wizard/kw_session_notify_wizard_view.xml',
        'wizard/kw_training_assessment_notify_wizard_view.xml',
        'wizard/assessment_result_send_mail.xml',
        'wizard/assesment_result_score_send_mail.xml',
        'wizard/session_attendance_wizard.xml',
        'data/training_session_notification_mail.xml',
        'data/kw_training_assessment_mail.xml',
        'data/assessment_result_mail_template.xml',
        'views/kw_question_bank_master_view.xml',
        'views/kw_auth_inherited_template.xml',
        'views/res_partner_view.xml',
        'views/res_config_settings.xml',
        'views/hr_employee_view.xml',
        'views/financialyear_wise_training_report_view.xml',
        'report/kw_participants_feedback_report.xml',
        'report/kw_participants_feedback_details.xml',
        'report/kw_trainer_feedback_details.xml',
        'report/session_attendance_report.xml',
        'data/training_module_access_cron.xml',
        'data/kw_training_calendar_approval.xml',
        'views/kw_training_calendar_nominated_approve.xml',
        'views/kw_training_calendar_view.xml',
        'views/kw_generate_certificate.xml',
        'report/pip_training_report.xml',


    ],
    'qweb': [ 'static/src/xml/*.xml',],
    'application': True,
    'installable': True,
    'auto_install': False,
}
    

