{
    'name': "Employee Appraisal",
    'version': '12.0.1.0.0',
    'summary': """Roll out appraisal plans and get the best of your workforce""",
    'description': """Roll out appraisal plans and get the best of your workforce""",
    'category': 'Kwantify/Human Resources',
    'author': 'CSM technology pvt.ltd.',
    'company': 'CSM technology pvt.ltd.',
    'maintainer': 'CSM technology pvt.ltd.',
    'website': "https://www.csm.tech",
    'depends': ['base', 'hr', 'survey', 'website', 'kwantify','kw_training'],
    'data': [
        'security/hr_appraisal_security.xml',
        'security/ir.model.access.csv',
        'data/mail_data.xml',
        'data/hr_appraisal_stages.xml',
        'data/kw_survey_type_data_appraisal.xml',
        'views/kanban_view_asset.xml',
        'views/appraisal_publish_wizard.xml',
        'views/hr_appraisal_form_view.xml',
        'views/kw_assessment_period_master.xml',
        'views/kw_appraisal_employee.xml',
        'views/self_appraisal.xml',
        'views/lm_appraisal.xml',
        'views/ulm_appraisal.xml',
        'views/kw_appraisal.xml',
        "views/kw_survey_template.xml",
        "views/kw_forbidden_error_templates.xml",
        "views/kw_survey_pages.xml",
        "views/kw_appraisal_goal_milestone.xml",
        'views/kw_goal_template.xml',
        'views/email/kw_appraisal_email_templete.xml',
        'views/hr_appraisal_survey_views.xml',
        'views/kw_survey_result_template.xml',
        'views/kw_survey_final_result.xml',
        'views/kw_survey_page_import.xml',
        'views/kw_surey_questions_import.xml',
        "views/kw_survey.xml",
        'views/kw_survey_score.xml',
        'views/appraisal_wizard.xml',
        'views/kw_survey_label_import.xml',
        'views/kw_archives.xml',
        'views/kw_employee_score.xml',
        'views/kw_goal_milestone_update.xml',
        'views/reminder_mail_sent.xml',
        'views/email/kw_lm_reminder_mail.xml',
        'views/email/kw_ulm_reminder_mail.xml',
        'views/email/kw_appraisal_result_template.xml',
        'views/kw_appraisal_achievement.xml',
        'views/templates.xml',
        'views/kw_appraisal_ratio.xml',
        'views/button_config_master.xml',
        'wizard/assign_appraisal_ratio.xml',
        'wizard/send_specific_increment_promotion.xml',

        # Appraisal reports
        'report/appraisal_pending_report.xml',
        'report/appraisal_progress_report.xml',
        'report/appraisal_all_perod_data.xml',
        'report/score_vs_increment_report.xml',
        'report/competency_report.xml',
        'report/employee_appraisal_progress_report.xml',
        'report/yearly_appraisal_progress_report.xml',
        'report/kw_appraisal_new_appraisal_emp.xml',
        'views/reports/appraisal_report.xml',
        'views/reports/appraisal_report_page_wise.xml',
        'views/reports/final_increament_report.xml',
        'views/res_config_settings.xml',

        # 'views/kw_self_previous_score.xml',
        # 'views/hr_url_menu.xml',
        'views/asset.xml',

        ##appraisal send mail
        'views/email/kw_employee_appraisal_draft.xml',
        'views/email/kw_self_to_lm_template.xml',
        'views/email/kw_lm_to_ulm.xml',
        'views/email/kw_reassessment_template.xml',
        'views/email/kw_final_approve_template.xml',
        'views/email/reminder_mail.xml',
        'views/email/kw_appraisal_reassessment_reminder.xml',
        'views/email/kw_goal_actions.xml',
        'views/email/kw_goal_update_apply.xml',
        'views/kw_appraisal_template_ratio.xml',
        'report/all_employee_data.xml',
        'wizard/process_increment_promotion.xml',
        'views/shared_increment_promotion.xml',
        
        'views/increment_master.xml',
        'views/appraisal_group_configuration.xml',
        'wizard/send_mail_by_create_date.xml',
        # cron data file
        'data/appraisal_cron.xml',
        'views/kw_appraisal_rule.xml'
    ],
    'qweb': [
        "static/src/xml/*.xml",
    ],
    'images': ["static/description/banner.jpg"],
    'installable': True,
    'application': False,
}
