# -*- coding: utf-8 -*-
{
    'name': 'BSSCL TDS',
    'version': '1.0.1',
    'summary': 'BSSCL TDS',
    'category': 'BSSCL/Human Resources',
    'author': 'CSM Technologies',
    'maintainer': 'Kwantify',
    'company': 'CSM Technologies',
    'website': 'https://www.csm.tech',
    'depends': ['base', 'hr', 'bsscl_hr_payroll', 'hr_contract', 'bsscl_fiscal_year'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/hr_contract_inherit.xml',
        'data/user_tds_fillup_mail_template.xml',
        'views/finance_tds_tax_computation_view.xml',
        'views/hr_declaration.xml',

        'views/user_tds_fillup_view.xml',
        'views/user_view_tax_bifurcation.xml',
        'views/yearly_hr_declaration.xml',
        'views/city_wise_hra_config.xml',
        'data/data_email_template.xml',
        'data/yearly_declaration_cron.xml',
        'data/hr_declaration_cron.xml',
        'data/it_rule.xml',
        'data/saving_master.xml',
        'data/income_tax_slab.xml',
        # # 'report/employee_service_book.xml',
        'views/tax_slab.xml',
        'views/tds.xml',
        'views/finance_approval_mail.xml',
        'views/monthly_declaration_report.xml',
        'views/yearly_notsubmitted_dec.xml',
        'views/hr_payroll.xml',
        'views/res_config_settings.xml',
        'views/compute_tax_action.xml',
        'views/digital_signature.xml',
        'data/config_parameter.xml',
        'views/all_hr_declaration.xml',
        'report/hr_declaration_report.xml',
'views/menu.xml',

    ],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
