# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Kwantify Grievance Management',
    'summary': """
        Kwantify Grievance
        """,
    'version': '1.0',
    'license': 'AGPL-3',
    'category': 'Kwantify',
    'author': 'Kwantify',
    'website': 'https://csm.tech',
    'depends': [
        'mail',
        'portal',
    ],
    'data': [
        'data/grievance_data.xml',
        'data/cron.xml',
        'security/grievance_security.xml',
        'security/ir.model.access.csv',
        # 'reports/grievance_reports.xml',
        # 'reports/report_format.xml',
        'reports/grievance_status_report.xml',
        'reports/whistle_blowing_report.xml',
        'wizard/incident.xml',
        'wizard/inprogress_remarks_wiz.xml',
        'wizard/awaiting_remarks_wiz.xml',
        'wizard/cancelled_remarks_wiz.xml',
        'wizard/done_remarks_wiz.xml',
        'wizard/new_team_assign_wiz.xml',
        'wizard/kw_whistleblowing_wizards.xml',
        'wizard/grievance_app_menu_wizard.xml',
        # 'wizard/grievance_report.xml',
        # 'views/assets.xml',
        # 'views/grievance_calltype_master_view.xml',
        'views/res_partner_view.xml',
        'views/grievance_ticket_templates.xml',
        'views/grievance_status_report.xml',
        'views/whistle_blowing_report.xml',
        'views/grievance_ticket_view.xml',
        'views/grievance_ticket_team_view.xml',
        'views/grievance_ticket_stage_view.xml',
        'views/grievance_ticket_subcategory.xml',
        'views/grievance_ticket_category_view.xml',
        'views/grievance_ticket_channel_view.xml',
        'views/grievance_ticket_tag_view.xml',
        'views/grievance_dashboard_view.xml',
        'views/report_grievance_ticket.xml',
        'views/res_setting.xml',
        'views/kw_whistle_blowing.xml',
        'views/grievance_ticket_menu.xml',

    ],
    'demo': [
        # 'demo/grievance_demo.xml',
    ],
    # 'development_status': 'Beta',
    'application': True,
    'installable': True,
}
