{
    "name": "STARLIGHT",
    "summary": "Kwantify STARLIGHT",
    "version": "12.0.0.0.9",
    "author": "CSM Technologies",
    "website": "http://www.csm.tech",
    "category": "HR Management",
    "depends": ["base", "hr","fetchmail","kw_resource_management"],
    "license": "",
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/award_notification_mail.xml",
        "data/rnr_schedulers.xml",
        "data/ir_sequence.xml",
        "data/general_configuration_data.xml",
        "data/reason_master_data.xml",
        'wizards/remark_wizard.xml',
        'wizards/update_user_wizard.xml',
        # 'views/res_config_settings.xml',
        "views/kw_rnr_report_views.xml",
        "views/kw_starlight_report.xml",
        "views/reward_and_recognition.xml",
        "views/take_action.xml",
        'views/kw_division_config.xml',
        "views/kw_Starlight_general_configuration.xml",
        "views/starlight_grade_config.xml",
        "views/starlight_reason_master.xml",
        "views/starlight_max_nomination_award.xml",
        "views/kw_reward_recognition_action_log.xml",
        'views/starlight_migration_log.xml',
        "views/employee_department_view.xml",
        "wizards/rnr_report_wizard.xml",
        "wizards/starlight_foward_to_next_month.xml",
        "wizards/congratulation_mailer_wizard.xml",
        "views/menu.xml",
    ],
    "demo": [
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}