# -*- coding: utf-8 -*-
from . import allowance_reports
from . import kw_ctc_report
from . import net_ctc_report
from . import employee_without_dependent
from . import professional_tax_report
from . import employee_pf_report
from . import employee_esi_report
from . import salary_disburse_report
from . import monthly_salary_report
from . import epf_calculatation_report
from . import bulk_esi_calculation_report
from . import epf_admin_charges_report
from . import employee_esi_calc_report
from . import salary_advance_report
from . import other_advance_report
from . import compiled_salary_report
from . import tds_report
from . import other_advance_download_report
from . import tds_report_download
from . import batch_wise_bulk_report
from . import salary_advance_report_download
from . import csmpl_compiled_salary_report
from . import c1_salary_report_filter
from . import form_12_b
from . import employee_dept_ctc_count_report
from . import kw_manpower_cost_report
from . import emp_health_insurance_emi_details
from . import ghi_details_report
from . import nps_pran_details
from . import nps_contribution_details