from . import it_rule_master
from . import hr_declaration
from . import n_hr_payroll
from . import yearly_hr_declaration
from . import city_wise_hra_config
from . import all_hr_declaration
from . import tax_slab
from . import tds
from . import yearly_notsubmitted_dec
from . import res_config_settings
from . import digital_signature
from . import hr_contract_inherit