from . import kw_advance_salary_remark_wizard
from . import kw_apply_petty_cash_wizard
from . import kw_apply_salary_advance_wizard
from . import kw_apply_petty_cash_remark_wizard
from . import kw_claim_settlement_remark_wizard
from . import kw_advance_claim_report_wizard
from . import kw_apply_claim_wizard
from . import kw_adv_pre_closer_wizard
from . import kw_adv_relaxation_wiz