# -*- coding: utf-8 -*-

{
    'name': "Kwantify Recruitment",
    'summary': "New Employee Recruitment",
    'description': "Employee Recruitment process",
    'author': "CSM Technologies",
    'website': "https://www.csmpl.com",
    'category': 'Kwantify/Human Resources',
    'version': '0.1',

    'depends': ['base', 'survey', 'hr_recruitment', 'website', 'website_hr_recruitment', 'hr_recruitment_survey',
                'kwantify', 'kw_web_notify', 'kw_project', 'kw_dynamic_workflow', 'kw_fiscal_year_sequence_extensible',
                'kw_skill_assessment', 'kwantify_theme','kw_resource_management'],
    'data': [
        'security/kw_recruitment_security.xml',
        'security/ir.model.access.csv',
        'data/MRF_ir_sequence.xml',
        'data/mif_ir_sequence.xml',
        'data/mail_mrf_template.xml',
        'data/mail_mif_template.xml',
        'data/mail_edited_mrf_template.xml',
        'data/hr_recruitment_data.xml',
        'data/data_source_master.xml',
        'data/data_stages.xml',
        'data/applicant_shortlist_mail.xml',
        'data/cron_kw_recruitment_job.xml',
        'data/mail_kw_hr_applicant_feedback_template.xml',
        'data/mail_kw_hr_applicant_meeting_template.xml',
        'data/data_kw_survey_type.xml',
        'data/survey_interview_feedback_forms_data.xml',
        'data/mail_kw_recruitment_mail_templates.xml',
        'data/mail_templates.xml',
        'data/tag_employee_mail_template.xml',
        'data/notify_to_rcm_mail.xml',
        'data/data_kw_qualification_master.xml',
        'data/mail_kw_job_applied_mail_template.xml',
        'data/mail_kw_job_applied_applicant_mail_template.xml',
        'data/mail_project_budget_confirm_in_applicant_template.xml',
        'data/mail_offer_letter_release_template.xml',
        'data/system_param_data.xml',
        'data/email_internal_job_posting_templates.xml',
        'data/email_applicant_screening.xml',
        'data/onboarding_payroll.xml',
        'data/update_budget_email_template.xml',
        'data/hr_discussion_applicant_details_pdf.xml',
        'data/hr_discussion_mail_template.xml',
        'data/hr_discussion_form_message.xml',
        'data/cv_rating_url.xml',
        'data/jd_skills_master_data.xml',

        'views/kw_recruitment_menu_access.xml',

        'report/kw_interview_feedback.xml',
        'report/offer_letter.xml',
        'report/offer_letter_lateral.xml',
        'report/offer_letter_ret.xml',
        'report/offer_letter_offshore.xml',
        'report/web_offer_letter_intern.xml',
        'report/web_offer_letter_lateral.xml',
        'report/web_offer_letter_ret.xml',

        'views/kw_calendar_event_view.xml',
        'views/assets.xml',
        # 'views/applicant_educational_and_work_experience_view.xml'

        "views/kw_website_job_apply_template.xml",
        'wizards/mrf_flow_view.xml',
        'views/kw_hr_job_view.xml',
        'views/kw_website_job_index_template.xml',
        'views/kw_website_job_detail_template.xml',
        'wizards/notify_wizard.xml',
        'views/kw_hr_applicant_finance_view.xml',
        'views/kw_hr_applicant_view.xml',
        'views/kw_hr_job_searchpanel.xml',
        'views/kw_ir_attachment_view.xml',
        # 'views/kw_website_menu.xml',
        # 'views/kw_survey_survey_view.xml',
        'views/survey_templates/kw_survey_result.xml',
        'views/survey_templates/kw_survey_template.xml',
        'views/survey_templates/kw_survey_question_widgets.xml',
        'views/survey_templates/kw_recruitment_mrf_success_form.xml',

        'views/kw_hr_job_positions_view.xml',
        'views/kanban_assests.xml',
        'views/kw_job_category_view.xml',
        'views/kw_industry_type_view.xml',
        'views/kw_qualification_master_view.xml',
        'views/kw_panel_members_master_views.xml',
        'views/kw_recruitment_location_view.xml',
        'wizards/kw_applicant_meeting.xml',
        'views/requisition_category_view.xml',
        'views/requisiton_skill_view.xml',
        # 'views/kw_requisition_view.xml',
        # 'data/workflow_recruitment_requisation_dynamic.xml',
        'views/mrf_recruitment_details_report_view.xml',
        'views/employee_referral_report_view.xml',
        # 'views/kw_recruitment_calender_report_view.xml',
        'views/kw_recruitment_new_joinee_report_view.xml',
        'views/kw_upcoming_new_joineee_report.xml',
        'views/kw_candidates_interviwed_report_view.xml',
        # added on 27 april
        'views/internal_job_opening_views.xml',
        # 'views/job_opening_applicant_view.xml',
        'views/ir_attachment_view.xml',
        'views/kw_calendar_event_attendee_view.xml',
        'views/kw_source_master.xml',
        'views/screening.xml',
        'views/settings.xml',
        'views/kw_recruitment_doc_store_view.xml',
        'wizards/kw_consolidated_feedback_wizard_view.xml',

        'views/kw_recruitment_experience_view.xml',
        'views/kw_recruitment_walk_in_meeting_view.xml',
        'views/mrf_approver_department_config.xml',
        'views/kw_mrf_employee_grade_access.xml',
        'views/kw_walk_in_meeting_details_view.xml',
        'views/kw_walk_in_applicant_view.xml',
        'views/kw_campus_applicant_view.xml',
        'views/job_application_offer.xml',
        'views/upload_cv.xml',
        'views/kw_notify_to_panel.xml',
        'views/cv_skills_master.xml',
        'views/cv_skills_api_log.xml',
        'views/cv_rating_api_response_log_view.xml',
        'views/jd_skills_master_view.xml',
        'views/screening_remainder_log.xml',
        # 'views/otp_log.xml',
        'views/survey_templates/kw_recruitment_offer_acceptance_template.xml',
        'views/recruitment_otp_assets.xml',
        'views/referred_employee_and_applicant_report.xml',
        'wizards/cv_screening_wizard_view.xml',
        # 'views/kw_mrf_views.xml',
        'data/rcm_validation_notification_mail_template.xml',
        'views/mrf_report_config.xml',
        'views/manpower_requisition_form.xml',
        
        'views/kwrecruitment_message_view.xml',
        'views/web_applicant_preinterview_data_template.xml',
        'views/sms/kw_applicant_otp_template.xml',
        'views/sms/kw_applicant_sms_template.xml',
        'views/kw_applicant_assets_frontend.xml',
        'views/web_applicant_edu_template.xml',
        'views/hiring_dashboard_views.xml',
        
        'views/web_applicant_work_experience_template.xml',
        # 'views/kw_applicant_assets_backend.xml',
        'views/new_employee_login_jd_template.xml',
        'wizards/mif_approved_wizard_view.xml',
        'report/mif_report_view.xml',
        'views/kw_manpower_indent_form.xml',
        'views/hr_discussion_applicant_details.xml',

        'report/ceo_reference_applicants.xml',
        'views/jd_skills_sequence.xml',
        
    ],
    'qweb': ["static/src/xml/hiring_dashboard.xml",
             "static/src/xml/aging_to_offer.xml",
             "static/src/xml/source_hire_rate.xml",
             "static/src/xml/offer_to_join.xml",
             "static/src/xml/offer_to_dropout.xml",
             "static/src/xml/infant_attration.xml",
             "static/src/xml/mrf_tagged_approved.xml",
             "static/src/xml/vacancy_dashboard.xml",
            ],
    'application': True,
    'installable': True,
    'auto_install': False,
}
