# -*- coding: utf-8 -*-
{
	'name': 'Reimbursement Stpi',
	'version': '12.0.1.0.0',
	'summary': 'Reimbursement Stpi',
	'category': 'STPI',
    'author': 'CSM Technologies',
    'company' : 'CSM Technologies',
    'website': "http://www.csm.tech",
    'maintainer' : 'CSM Technologies',
	'depends': ['base','hr','bsscl_recruitment','bsscl_employee','date_range'],
	'data': [
		'security/security.xml',
		'security/ir.model.access.csv',
		'data/reimbursement_type_data.xml',
		# 'security/reimbursement.xml',
        # 'views/reimbursement.xml',
        'views/reimbursement_main.xml',
        'views/reimbursement_attendence.xml',
        'views/late_coming_report.xml',
		# 'wizard/multi_approve.xml',
		# 'wizard/late_coming_wizard_view.xml',
		'report/late_coming.xml',
		'views/reimbursement_type_views.xml',
		'views/payment_advices.xml',
		'views/payment_advice_report.xml',
		'views/hr_job_views.xml',
	],
	'images': [],
	'license': 'AGPL-3',
	'installable': True,
	'application': False,
	'auto_install': False,
}