# -*- coding: utf-8 -*-
from . import kw_emp_profile_family_info
from . import kw_emp_profile_identity_docs
from . import kw_emp_profile_work_experience
from . import kw_emp_profile_educational_qualification
from . import kw_emp_profile_technical_skills
from . import kw_emp_profile_membership_assc
from . import kw_emp_profile_language_known
from . import kw_emp_profile
from . import kw_emp_profile_new_data
from . import kw_emp_profile_inherit_hr_emp
from . import kw_emp_profile_cv_info
from . import emp_profile_wizard
from . import kw_employee_pan_update_log
from . import res_config_in
from . import add_employees_to_ra
from . import appraisal_details_docs
from . import kw_cdp_category
from . import kw_hr_job_cdp
from . import organisation_commitee
from . import kw_emp_new_cv_info
